package com.vtxlab.demo.helloworld.demo_sb_customer.repository;

import org.springframework.stereotype.Repository;
import com.vtxlab.demo.helloworld.demo_sb_customer.entity.CustomerEntity;
import org.springframework.data.jpa.repository.JpaRepository;

// JPA + Driver (Postgresql)
// ! Hibernate generates the implementation class, which implements "CustomerRepository"
// 使用 JPA 和 Hibernate 框架來操作資料庫的 Repository 介面 CustomerRepository
@Repository // bean
public interface CustomerRepository extends JpaRepository<CustomerEntity, Long> {
  // ! During maven compilation, the implementation class is generated by Hibernate
  // save()
  // saveAll()
  // findAll()
  // findById()
  // deleteById()
}
